language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

php:
  - 7.0
  - 7.1

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
